### ISSUE TITLE
Multiple venues per business submitted status

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#11]
Additional businesses that have been added but no approved should still be shown on the right hand sign. Showing (pending approval)

I believe this was working previously and has been modified as part of the refinement.
cc: @MaximilianArasin

**Comment by MaximilianArasin** [comment]
Any updates on this please?
@rcoppa 
@multidimensionro

**Comment by multidimensionro** [comment]
HI @rcoppa @MaximilianArasin,

This is working now.

Best regards,
Darius-Sorin Bodescu
