### ISSUE TITLE
My Backend login + data that has been deleted is still stored

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#12]
Hey @rcoppa 

my http://getintoapp.com/admin/index/login does not work for max@getintoapp.com anymore.
![screenshot_10](https://cloud.githubusercontent.com/assets/11382000/6748035/74970a9e-cee1-11e4-80b3-11d55ccbab86.jpg)

I am listed as talent but not as user. Not sure what the issue is here, maybe you can help?
Also do we have a solution for the storage issue? What happens if we delete user data in order to reset a users account, setting up the same user again the system would not allow this since data is still stored somewhere and blocked in the backend. Maybe we can host separately so that data is still in a safe house somewhere but not linked permanently to the operating backend? No idea if this makes sense.

Thanks and cheers
Max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin @rcoppa,

This has been implemented on both live and staging.

When an account is deleted the email is saved in a different column, so the email is cleared for use.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
Great thank you!
