### ISSUE TITLE
low prio: Update http://getintoapp.com/docs/Into_business_info.pdf 

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#13]
@multidimensionro  I will send you and reuben an updated file with my german contact details. please upload this. cheer max

**Comment by multidimensionro** [comment]
@MaximilianArasin  

Please provide the PDF

**Comment by MaximilianArasin** [comment]
@multidimensionro I sent it through to you and Reuben via email a week ago. Here you go again:

https://www.dropbox.com/s/7tqnbnvm7u62cma/Into%20pre-launch%20info.pdf?dl=0

cheers
Max

**Comment by multidimensionro** [comment]
@MaximilianArasin @rcoppa 

The PDF has been updated at the same link.

**Comment by MaximilianArasin** [comment]
@multidimensionro sorry there are spelling mistakes. could you please update again to the following document?! Thanks

https://www.dropbox.com/s/rv823jaod3sr056/Into%20pre-launch%20info.pdf?dl=0

**Comment by MaximilianArasin** [comment]
@multidimensionro has this been done? just checking. thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

The PDF is the one updated.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
thx
