### ISSUE TITLE
HIGH PRIO: Social sharing text to add + Instagram

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#16]
Sign Up Process – connect to social networks – we need more info here for the user. At this point a user will still be sceptical on why to connect to social media networks. Below the text on this screen "we never post anything without .... " we should add a link saying "see why" which links to the text from our not-sharing screen. Sharing is caring. See attachment 140902_design_6_27 (to change in app)

**Comment by rcoppa** [comment]
![140902_design_6_27](https://cloud.githubusercontent.com/assets/1256325/6954183/bc48a0b2-d91a-11e4-95f5-a665cb28c0e4.png)

**Comment by MaximilianArasin** [comment]
I am meeting Hardy on Monday/Tuesday and will send over the updated png for you to implement.
cheers

**Comment by MaximilianArasin** [comment]
@rcoppa I will talk to Hardy first and let you know. Cheers

**Comment by MaximilianArasin** [comment]
Hi @rcoppa @multidimensionro we added the text on the same screen. Now it looks really sleek. This will hopefully prevent user from not connecting her social networks. Please use the file below via download.

https://www.dropbox.com/s/pj8jeg1zfxmo24a/150407_designs_04.eps?dl=0
https://www.dropbox.com/s/kd2oaoysovfr2tl/150407_designs_04.png?dl=0


let me know if you need anything else.
CHeers
Max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been added.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
@multidimensionro the "sharing is caring" text is not a block as per design provided (see above).
Also Instagram does not appear ??? This was meant to be fixed in release 1.1 , want it?

I will move this to milestone 1.2 so that this can be fixed, please.

thanks and regards
Max
