### ISSUE TITLE
HIGH PRIO: History showing redeemed offers for brand new users

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#17]
History - 

Already redeemed offers for brand new users??? 

Jess: Rolling fix, Hilton , 
Brian: Farmhouse – 

why are these offers showing up as history if the users has never even been on the app before? (might be backend related – deal usage limit reached)

@Intolucas please upload screenshots and provide user details.
cc @MaximilianArasin

**Comment by Intolucas** [comment]
![history screenshot jessica noakesmith](https://cloud.githubusercontent.com/assets/11762295/6954441/9d23e7ca-d91d-11e4-8292-916bde149ba7.jpg)

**Comment by Intolucas** [comment]
she only redeemed the first one - the other were already there - showed up for Brian Fear as well

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed.

It was API related.

Best regards,
Darius-Sorin Bodescu
