### ISSUE TITLE
HIGH PRIO: password reset only possible after entering wrong one

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#18]

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

Can you please notify me if this is part of the application or of the backend?

And how exactly would you like this to work?

Best regards,
Darius-Sorin Bodescu

**Comment by multidimensionro** [comment]
@MaximilianArasin 

Can you please provide the details requested above.

**Comment by MaximilianArasin** [comment]
@multidimensionro okay I think is was about the application. Tonight we will have this screen as the start screen on our app:

![150407_designs_05](https://cloud.githubusercontent.com/assets/11382000/7157812/7f8d15f0-e373-11e4-9230-23e9367f1593.png)

**Comment by MaximilianArasin** [comment]
What happens if a user types in a wrong password and can't  remember his password....do we have a link coming up : reset password?

I know we had this in place on the very first release to apple.

Let me see if I find it...otherwise Marcel should have this....we need to give the user somehow the opportunity to reset their password if they created an account already. don't you think?

thx and cheers
Max

**Comment by MaximilianArasin** [comment]
![140902_design_6_8](https://cloud.githubusercontent.com/assets/11382000/7157942/a72e9d8a-e374-11e4-8ec5-fa96c9e77269.png)

**Comment by MaximilianArasin** [comment]
I am sure this issue was related to the fact that this section "I`ve lost my password, please send me a new one" only appears when you click on password and enter a wrong one. The section is not there by default ....like for examplefacebook does it: 

![screenshot_06](https://cloud.githubusercontent.com/assets/11382000/7158042/df8c660c-e375-11e4-9fd5-cb105e75563e.jpg)


Maybe talk to Marcel and find out what solution he has.

thx and cheers
max

**Comment by MaximilianArasin** [comment]
maybe we just display "forgot password" as a link below "sign in" just like we do it on web. see below:

![150407_designs_05](https://cloud.githubusercontent.com/assets/11382000/7158167/8ee1c6fa-e377-11e4-8367-e74734aef42c.png)


![screenshot_07](https://cloud.githubusercontent.com/assets/11382000/7158195/da0a41de-e377-11e4-82dc-d6b5ad013339.jpg)

Depends on what marcel says. here is the following screens as well:

![140902_design_6_9](https://cloud.githubusercontent.com/assets/11382000/7158221/16d66228-e378-11e4-9fed-0a83351708c4.png)
