### ISSUE TITLE
HIGH PRIO: login button border looks broken.. outline should be solid

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#19]
![button](https://cloud.githubusercontent.com/assets/11382000/6983119/77373780-da1a-11e4-89ba-fb80f9f07e15.png)

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro just spoke to Hardy. The idea of the button was to be animated with a glow. To drive the user towards activating the offer. Please have a look at the video below. It shows the glow "slide to unlock"

https://www.dropbox.com/s/x1zbkxpmjc1isdq/animation%20bug%202%20low%20quality.mov?dl=0

We have two options. 1. Make the button crisp and not broken 2. make it crisp and add the glow animation. What ever is quicker and possible. Up to you. Worst case we add the glow at a later stage.

thanks and cheers
Max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been handled using the first option.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro looking good.
I am closing this issue. Maybe further down in a couple of weeks we can update to the animated option.

But all good for now.
Thx and cheers
Max
