### ISSUE TITLE
HIGH PRIO: no internet connection

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#21]
what happens if there is no internet connection and users are opening the app?
different messages are coming up. red app pop ups and apple design pop up.This is misleading.

![no internet connection1](https://cloud.githubusercontent.com/assets/11382000/6983299/8adc6772-da1c-11e4-9d0f-5b1c2818d021.png)
![no internet connection2](https://cloud.githubusercontent.com/assets/11382000/6983320/b8847d22-da1c-11e4-9c9a-585a437b70bf.png)

Google maps has just one pop up saying no network connection --> see below.
![no network connection on google maps](https://cloud.githubusercontent.com/assets/11382000/6983339/dedd1f2e-da1c-11e4-81cb-b21a86895eec.png)

I think it is a good idea to handle it the same way. Simple and clear.

to do: please use one error message for all scenarios (app opening, app opening from running in the background, etc) saying: No network connection.

cheers

**Comment by multidimensionro** [comment]
@MaximilianArasin 

Marcel has notified me this has been completed in the current dev app. We will test once a dev IPA is available.
