### ISSUE TITLE
1.2 LOW PRIO: Select a category - to have a search functionality (magnifier)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#24]
Select a category - to have a search functionality (similar to History - magnifier top right corner) 

@rcoppa We would need an estimate for this. To implement this exact same functionality from our history screen to the main app page would significantly increase the usability and orientation for our users. And I believe it is a quick small fix for us. I will discuss this issue with Hardy as well on Monday/Tuesday and give you feedback. Would be good to have an estimate to see if it is worth it. cheers  

![search functionality1](https://cloud.githubusercontent.com/assets/11382000/6986384/fef9e1dc-da3c-11e4-9550-1f699b9460fc.png)

![search functionality 2](https://cloud.githubusercontent.com/assets/11382000/6986408/3f55e9ce-da3d-11e4-92e8-71e9f0060f92.png)

![search funtionality3](https://cloud.githubusercontent.com/assets/11382000/6986414/4f18d088-da3d-11e4-8d8f-a338a365462c.png)

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro @rcoppa we added the search functionality to the main screen. By default "select a category" should display: Select a Category (just like in the file below) - and not Nearby. But it should still show all offers (like it currently is with nearby). "Nearby" would be part of the categories in the dropdown menu. This makes great sense since the user now gets guided towards the button "select a category". Please find the files here:

https://www.dropbox.com/s/wejks2c6kngjxpo/150407_designs_01.eps?dl=0

https://www.dropbox.com/s/7nnihcmlkakp05g/150407_designs_01.png?dl=0

Please let me know if you need anything else.

Cheers
Max

**Comment by multidimensionro** [comment]
@MaximilianArasin 

Marcel will need around 4-5 hours for this. Please advise if this is approved.

**Comment by MaximilianArasin** [comment]
I will discuss with @Intolucas and let you know asap. I think it is a great improvement and maybe if we are lucky Marcel can do it in 3-4 h.

**Comment by MaximilianArasin** [comment]
@multidimensionro it is approved. Please go ahead.

**Comment by MaximilianArasin** [comment]
Search functionality in map view doesn't work yet. Lets brainstorm and find a solution soon together. google maps shows us how it has to work. Conversation with Darius below:

![screenshot_09](https://cloud.githubusercontent.com/assets/11382000/7204872/b5be8af6-e525-11e4-84e4-1f9483f2a9fa.jpg)

![screenshot_10](https://cloud.githubusercontent.com/assets/11382000/7204901/fa92c070-e525-11e4-8b34-215f8c5dfe79.jpg)

![screenshot_11](https://cloud.githubusercontent.com/assets/11382000/7204909/0c7a9358-e526-11e4-83aa-2ccc86074bdf.jpg)

![screenshot_12](https://cloud.githubusercontent.com/assets/11382000/7204923/22b71614-e526-11e4-8ce2-4bd43dcf117c.jpg)

![screenshot_13](https://cloud.githubusercontent.com/assets/11382000/7204938/34f5c88e-e526-11e4-9188-b832dc62e89c.jpg)

**Comment by multidimensionro** [comment]
@MaximilianArasin,

Here is Marcel's quote for handling the map linked view:

From our point of view we don't see any issues with search functionality on map. The only thing that we think it's not very intuitive is that the map is not interactive when new text is queried. But this doesn't mean that is not working at all.

Following your suggestion we are thinking that this would require embedding a new table view that will display all suggestions according with the searched text, which user will be able to scroll and select the location/deal and the map will redirect there.

Estimated time: 3 hours.

**Comment by MaximilianArasin** [comment]
please implement this search functionality on the map view properly as discussed for 1.2

thx and regards

**Comment by MaximilianArasin** [comment]
@multidimensionro just checked on the current build. Please find my following comments:

A. once you start typing results should show up. by default before you start typing into the search field there should be no results listet since we havent started searching. Just like in IOS spotlight search. No type - no results. 
![img_7560](https://cloud.githubusercontent.com/assets/11382000/7364367/1525e634-ed86-11e4-837a-88537168db25.PNG)

B. there is a white layer visible under the search results ... please double check and make this crisp. Also the background is grey instead of the map. please fix. thx
![img_7561](https://cloud.githubusercontent.com/assets/11382000/7364399/5f049dc2-ed86-11e4-810c-806f4a2df7e3.PNG)

C. there is no map in the background. it is just grey....please check and fix. cheers
![img_7562](https://cloud.githubusercontent.com/assets/11382000/7364422/961316fe-ed86-11e4-9545-3d8548244c70.PNG)

**Comment by multidimensionro** [comment]
Hi Max,

Here you can find Marcel's  responses:
A. Fixed.

B. there is a white layer visible under the search results ... please double check and make this crisp. Also the background is grey instead of the map. please fix. thx
Answer: Fixed. The background is grey because the position on the map is on the ocean area.

C. there is no map in the background. it is just grey....please check and fix. cheers
Answer: That is the map. The background is grey because the deal is in the middle of the ocean ( it's coordinates are 0, 0 ). Please check by zooming out in the map.

Best regards,
Darius-Sorin Bodescu
