### ISSUE TITLE
HIGH PRIO: 1.1 + 1.2 Sign up - first name + last name fields are not same size as gender 

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#25]
to do: match size of boxes. Currently gender and birth date are wider then first name and last name box.
I will double check this screen with hardy on monday and possibly provide you with a new png. Otherwise you will have to match the boxes but I will give you input before. thx and cheers

![set up your profile box too small](https://cloud.githubusercontent.com/assets/11382000/6987699/48491e36-da4a-11e4-932d-61a6ad8ff8ea.png)

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro to make your life easier we updated this screen and matched the frames. Please use the file below via download. It comes now with correct spacing, only one arrow and matching frames.

https://www.dropbox.com/s/w05ki37tfo8p51e/150407_designs_03.eps?dl=0

https://www.dropbox.com/s/wvdowi4rvlu7eea/150407_designs_03.png?dl=0

let me know if you anything else.
cheers
Max

**Comment by MaximilianArasin** [comment]
@multidimensionro please use the provided layout for male/female and birthday in the set up procedure. currently the layout looks in the setup the same as in profile and settings for the user:

![img_7478](https://cloud.githubusercontent.com/assets/11382000/7317976/5607c61a-ea87-11e4-92a0-6160b5911108.png)

please also make sure that under profile & settings the tow field are closer together. Just like the other fields are always sitting together. the headline gender and birthday is fine in this case.

please update this in 1.2

thx and regards

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed. Please advise.

Best regards,
Darius-Sorin Bodescu
