### ISSUE TITLE
HIGH PRIO: Intro animation – Into icon is jumping 

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#26]
Into Icon is jumping while map is zooming in. Would be good to make this smooth.
Please see video via link:
https://www.dropbox.com/s/x1zbkxpmjc1isdq/animation%20bug%202%20low%20quality.mov?dl=0 

thx and cheers
Max

**Comment by multidimensionro** [comment]
@MaximilianArasin @rcoppa 

Marcel has notified me this has been solved in the latest version: http://install.diawi.com/JW8VxK

**Comment by MaximilianArasin** [comment]
great. thx
