### ISSUE TITLE
LOW PRIO: Not sharing screen – text to layout as a block (aligned left and right)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#27]
@rcoppa I will discuss with Hardy first on Monday/Tuesday and let you know if this is an issue. We would then need a cost estimate since this is an enhancements to the original design. But I will let you know in two days. Cheers

![140902_design_6_27](https://cloud.githubusercontent.com/assets/11382000/6992426/9832dd00-dacd-11e4-8cb8-96c3961a255c.png)

**Comment by MaximilianArasin** [comment]
Please find the updated file with text in proper block layout below via download. In comes as .png and .eps.

https://www.dropbox.com/s/6lofvpuo33zoj50/150407_designs_02.eps?dl=0

https://www.dropbox.com/s/m74u1ftiz0zprd4/150407_designs_02.png?dl=0

let me know if you need anything else.

cheers
Max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been completed and it's part of the new app submission.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
@multidimensionro I just double checked this in 1.1 and the logo color is implemented which is great but the text is not yet as per design (see dropbox file above). It is meant to be a text block. Would be great if we can fix this in 1.2

screenshot current layout 1.1 - no block layout:

![img_7470](https://cloud.githubusercontent.com/assets/11382000/7296444/0d9d2680-e9c0-11e4-980c-fb5b5e88478e.png)


great. thank you

**Comment by MaximilianArasin** [comment]
text block intended to look like this:

![150407_designs_02](https://cloud.githubusercontent.com/assets/11382000/7296466/40f68332-e9c0-11e4-8f8d-1597adfd6c19.png)
