### ISSUE TITLE
HIGH PRIO: User menu "Help" wording (text)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#29]
User menu - "Help" to change the wording to "Help & Recommendations"

@rcoppa This is an enhancement and we would need an estimate for this. I assume this is very minor since it is literally adding one word (text) to the column. The functionality with the link to email will stay exactly the same. Please let me know if I need to get Hardy to add the word or if you can just change the wording yourself. For the other column you changed the wording earlier already so I hope Hardy is not necessary here.

thx and cheers

 
![user menu into logo black](https://cloud.githubusercontent.com/assets/11382000/6992491/8c353926-dad2-11e4-83a0-cb0cc04609e9.png)

**Comment by multidimensionro** [comment]
@MaximilianArasin 
This has been done in the latest stating version: http://install.diawi.com/JW8VxK

**Comment by MaximilianArasin** [comment]
thx. Great!
