### ISSUE TITLE
Download soon - www.getintoapp.com - to be linked to app store

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#30]
Hi @multidimensionro , please link the button on our website to the app store so that downloading actually works. We should do this once release 1.1 is live. But we can do it also earlier if the link to apple stays the same regarding 1.0 (actual version)and 1.1 (soon to come).

thx and cheers
Max

![screenshot_19](https://cloud.githubusercontent.com/assets/11382000/7041902/bd0fa35c-dddd-11e4-9951-63aee442bd76.jpg)

**Comment by multidimensionro** [comment]
@MaximilianArasin 
This has been linked. I have discussed with Marcel and the link will remain the same for v1.1 as well.
