### ISSUE TITLE
HIGH PRIO: User menu - Profile & Settings --> text/layout to change

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#31]
Hi @multidimensionro please change the layout/text to match the intended design:

![profile settings bug](https://cloud.githubusercontent.com/assets/11382000/7087814/967e4820-df8f-11e4-929c-c52305c3b153.png)

to do: 
A. change "Gender and Birth Date" to "Gender and Birthday"
B. delete the word "Birthday" (sitting in between Male/Female and 05/03/1987)
C. place the birthday field (05/03/1987) next (under) male/female field (where "Birthday" is currently sitting.)

happy to confirm once its done .. I downloaded the latest build.
thx and let me know if there are any questions

cheers
max

**Comment by multidimensionro** [comment]
HI @MaximilianArasin,

This has been completed and it's part of the new app submission.

Best regards,
Darius-Sorin Bodescu
