### ISSUE TITLE
URGENT: Error with licence/payment fast spring

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#32]
Please see conversation with fast spring below. Any idea why payment is not working properly? In our backend for this client it says that payment has been done, but fast spring says licence generator failed??? Help please! thx max

Julie E (FastSpring), Apr 13, 4:46 AM:
Max,

The license generator failed to retrieve a license for that order, and an earlier order. So when we send to http://www.icmpoker.com/fastspringsubscriptionservice/fastspringservice.svc/generate_license something is wrong because we aren't receiving a license. Discounts would not effect this, but I'd be happy to look at them if you tell me what they are called and what you wanted them to do, so I can see if they are set up properly.

Lucas Foertsch (getintoapp), Apr 13, 4:38 AM:
Hi,

we just got an error message concerning a subscription. Maybe you can help and let me know what the reason is for this. Do we have to change any settings maybe? Also I created some more discounts in fast spring. Is that all okay? Do they all work properly?

Your help is much appreciated. Please email me back directly --> max@getintoapp.com ( the address of my business partner lucas@getintoapp.com is setup in fast spring as contact)

please find the error message below:

License generator did not have results. (dispenser=LicenseDispenser[a_vyjbfiTxKNFPFgMcQUzA,])
-- REQUEST --
POST /index/paymentData HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
User-Agent: FS
Host: getintoapp.com
Content-Length: 384
company=F45+Training+Pyrmont&email=mmarsh%40f45training.com.au&internalProductName=Into+App+Monthly+Subscription&name=F45+Training+Pyrmont&pass_key=881c4cd399e9f1b33b29e92ffecc7473&quantity=1&reference=GET150413-9133-41167&referrer=http%3A%2F%2Fgetintoapp.com%2Findex%2Fform&subscriptionReference=GET150413-9133-79181S&test=false&security_request_hash=5a4ddb5064b37bc755e679ced9a8c865

-- RESPONSE --

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed, and based on our tests on Friday it can be closed.
