### ISSUE TITLE
HIGH PRIO: multiple businesses bugs and fixes

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#33]
A: fast spring: credit card details error
When you enter your credit card wrong it doesn’t delete the details… is this safe?

Every other website I have ever been on deletes the details before allowing you to re-enter… just thought I’d say something! ---> I think this is a fast spring issues. If you agree then just ignore issue "A".

![screen shot 2015-04-16 at 10 30 00 am](https://cloud.githubusercontent.com/assets/11382000/7176930/14b99a36-e423-11e4-8910-1862312ec644.png)

**Comment by MaximilianArasin** [comment]
B: Feedback from tester:
I created a multiple business called zac test and went through payment using 12 month free voucher

Then I added 3 more businesses and approved them in the backend

When I went into zac 2 test and clicked payment it had the correct amount (3) of licences for me to buy… but once I was re-directed back to the into page the other 2 businesses (zac 3 and zac 4) still say payment pending??

![screen shot 2015-04-16 at 10 42 17 am](https://cloud.githubusercontent.com/assets/11382000/7176986/7d6511f0-e423-11e4-93e0-7386ced167c0.png)

**Comment by MaximilianArasin** [comment]
C: email message from backend:
tester feedback: Why did I get this for Zac Test offer upload???

And why can’t I see the offer on the list now??? I added 3 images and approved the offer???

Hi Lucas,

Done! Your business offer is now live on Into App.
Soon you will see our users coming to your doorstep and sharing their experiences.

How to recognise our users? How does the redemption in your venue work again? Please find a quick guide for you and your staff here.

Any questions? Please get in touch via partners@getintoapp.com.
We are always here to listen and help.

Your Into Team

**Comment by MaximilianArasin** [comment]
D: update message:
tester feedback: When you click on “Update” under the account section in one of the additonal businesses added it gives this update

![screen shot 2015-04-16 at 10 43 02 am](https://cloud.githubusercontent.com/assets/11382000/7177180/d0bc5538-e424-11e4-99d3-78665e6a637e.png)


to do: since we are hiding the password field now on added businesses this error/update message doesn't make sense. Maybe we just say "Update successful" like we do in the app in profile&settings? thoughts?thx

**Comment by MaximilianArasin** [comment]
E: feedback from another tester. Interesting getting these important insights:

Ok so this is my experience as a “business user"

I apply for an account trhough the webiste
I receive my notification that it is being processed
I am advised by email from INTO that I need to add additional businesses under this account on the right hand side of the screen
Then I need to wait for INTO to approve these additional businesses 
I did not receive an email from INTO saying that they are approved
I logged back in to see if anything had changed and only 2 of the 3 were approved (see screenshot and email to show that I did chose 3 subscriptions) 

![screen shot 2015-04-16 at 12 24 40 pm](https://cloud.githubusercontent.com/assets/11382000/7177346/3597d026-e426-11e4-934e-22bd6e763ff2.png)


to do: a: change text for add business to "+ add additional business (optional)"
b: I am advised by email from INTO that I need to add additional businesses under this account on the right hand side of the screen --> what is this email? what if someone has only one business ? can you please provide me with this email so I can double check? thx
c: I did not receive an email from INTO saying that they are approved --> I think I provided you with email content here? please let me know.thx
d: I logged back in to see if anything had changed and only 2 of the 3 were approved (see screenshot and email to show that I did chose 3 subscriptions) --> why is this? maybe you have a clue? thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin 

The above issues have been fixed.

Best regards,
Darius-Sorin Bodescu
