### ISSUE TITLE
MID PRIO: Website/Business section: ticks to be set up properly

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#35]
ticks to be sitting where information has been correctly pre-filed. (additional businesses)

![screenshot_03](https://cloud.githubusercontent.com/assets/11382000/7183164/1f3e7d68-e456-11e4-8805-fac3499f6d65.jpg)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed.

Best regards,
Darius-Sorin Bodescu
