### ISSUE TITLE
LOW PRIO: Add numbers to headlines (business section)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#36]
Please as discussed add numbers to the headlines as in the attachment below. Let me know if that is okay for you and quickly to do. thx

![screenshot_08](https://cloud.githubusercontent.com/assets/11382000/7201609/67a7dbb8-e509-11e4-9097-d2afa9499490.jpg)

**Comment by MaximilianArasin** [comment]
p.s. number dot space word --> 1. Account (for example)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

The numbers have been set. 

Best regards,
Darius-Sorin Bodescu
