### ISSUE TITLE
HIGH PRIO: Password generation first time business - bug

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#37]
received message. 
clicked on link.
landed here http://getintoapp.com/index/resetpasword?token=$2y$10$ZjDZWiSTPaaNrI1tIWyNpeB2LfWHZilso.2wgQCeHp37HrQxpQTRS_

tried to generate password.
following error message popped up:

![screenshot_05](https://cloud.githubusercontent.com/assets/11382000/7201657/051451c4-e50a-11e4-9e76-f65727a7e1a8.jpg)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

We fixed the error in the link generation and now this works properly.

Best regards,
Darius-Sorin Bodescu
