### ISSUE TITLE
HIGH PRIO: Upload pictures doesn't work - bug

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#38]
Uploaded 6 pictures and only 1 showed up in the backend.
please see email including the pictures . let me know if you need anything else.

cheers
Max

**Comment by MaximilianArasin** [comment]
@multidimensionro  did we find out about what caused this issue? can we close this , please?

thx and cheers

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed.

The issue can be closed.

Best regards,
Darius-Sorin Bodescu
