### ISSUE TITLE
HIGH PRIO: Picture upload error message

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#39]
As discussed please set the size of every image on a max. of 5MB. If individual images uploaded are too big...there should be instantly an error message. Currently error message does not show up. And if it shows up it shows only up once "apply" at the end of the offer setup has been clicked.

thx

**Comment by MaximilianArasin** [comment]
@multidimensionro did we decide on the max size of images? does the error message work now?
please provide me with info so that we can add to the text and close the case.

thx

**Comment by multidimensionro** [comment]
@MaximilianArasin 

Hi Max,

This is in. The error is set to appear if the image has over 5Mb.

Best regards,
Darius-Sorin Bodescu
