### ISSUE TITLE
URGENT: multiple business was sitting in the backend before parent business worked and needs to be set up now

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#41]
Lucas feedback:

Ok so I went in and approved “First Vintage”
Then I went and apprived “Bootleg Liquor” and made “First Vintage” the parent business
Now I can log in using angela@creativecherry.com.au any more!
I tried deleting the bootleg account but it didn’t help
Bootleg data here in screenshot

**Comment by MaximilianArasin** [comment]
![screen shot 2015-04-21 at 12 22 52 pm 2](https://cloud.githubusercontent.com/assets/11382000/7247507/73f6d1c2-e80a-11e4-8b0f-b3b7210baffe.png)

**Comment by MaximilianArasin** [comment]
her upcoming businesses needs to be approved so that we can send her login details for business login section so that she can do her payment and set up her deals.

parent business:
first vintage

childen:
http://getintoapp.com/admin/index/businessAdd?temp_business=67
bootleg liquor

**Comment by MaximilianArasin** [comment]
please use the password for her parent business: getinto99

**Comment by MaximilianArasin** [comment]
p.s I cannot see bootleg liquor and first vintage under "upcoming businesses" anymore ... the data seems to be lost after lucas tried to approve them.

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been recovered, including the upcoming business provided this morning, which will need to be approved by you.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
thank you
