### ISSUE TITLE
URGENT: App 1.1 is landing by default on Sydney not the closest City in our network (Berlin)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#43]
...maybe this is okay since only Sydney is active with content as a INTO-City. 
 Anyway maybe double check this issue on the app.

thanks

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

Marcel has told me that:

A feedback sent on 13/02 specifically said " why is Seaforth (current location) now a permanent tab even if I close the app and open again. current location name should only be displayed if the plane is activated. "

In this case the default city selected is Sydney every time the app opens or a user logs in. 

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
yes all good. We agreed on a setting by default that displays the closest INTOactive city . Since we only have Sydney as active....this is all good
