### ISSUE TITLE
first time user login to app - user gets logged out and in again

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#46]
hi @multidimensionro 

just had a app (1.1) test with a new user (agency code). Login works. Instagram is missing. after all fields are filled out I land here again: 
![img_7486](https://cloud.githubusercontent.com/assets/11382000/7318213/a0fe7982-ea89-11e4-98f1-8a62c73eb8a6.png)

afterwards is start loading the intro animation and it says welcome back. 

to do: the first time user set up process is great. after this is completed by the user it should say instantly welcome (not welcome back!) and without landing on the screen above (see above) the intro animation should start.

for someone who is not a first time user - the welcome back animation is fine of course.

please let me know your thought and implement if possible in 1.2

cheers and thanks
max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed.

Best regards,
Darius-Sorin Bodescu
