### ISSUE TITLE
URGENT: set up an offer that is available to the user once a week, once a month, once every two month? 

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#53]
This has always been discussed and agreed on:

We need to be able to set in the backend that an offer is redeemable only once a week, once a month and even once  every two month. If we just extend the redemption period that would allow the user to walk into a cafe and pic unlimited coffees a week. 

This is very critical as allowing offers for businesses is pointless otherwise.
Please advice and implement a field for this in the backend.

thanks

**Comment by MaximilianArasin** [comment]
ideal would be daily, weekly, fortnightly, monthly, once every two month. that should cover all the cases we initially discussed.

thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

There is a new field called: Times Redeemable Extra: in the backend. You can set this at that location.

The application handles this.

Best regards,
Darius-Sorin Bodescu
