### ISSUE TITLE
low prio: app crashes while activating offers in the backend

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#54]
just activating upcoming offers and tried to login to the app to double check the offer are layette nicely.

When I close the app and open again the app freezes. sometimes the app won't even close if I press the home button.

will add images shortly

**Comment by MaximilianArasin** [comment]
update: app doesn't open at all anymore. can you open the app on your devices? On my device it shows the Into icon for 4 seconds and then closes down.

**Comment by multidimensionro** [comment]
@MaximilianArasin Are we talking about the live app?

**Comment by MaximilianArasin** [comment]
Happened at the airport in a public wifi with live app. Now it's not happening anymore.

**Comment by MaximilianArasin** [comment]
Might have been a rare case. Let's work on it if it happens again... Maybe leave it for now but good to have it in here. Thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

I would suggest you open this as a different task if it happens again. Currently it could not be reproduced.

Best regards,
Darius-Sorin Bodescu
