### ISSUE TITLE
Urgent: 1.3 app city menu shows strange cities

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#56]
![city bug](https://cloud.githubusercontent.com/assets/11382000/7587228/15cef622-f8b5-11e4-80ed-d2a8075d18ed.png)

**Comment by MaximilianArasin** [comment]
paddy river must have been pulled from one of the businesses/offers. Lucas found out it must come from http://getintoapp.com/admin/index/businessEdit?business_id=166

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin, @Intolucas, @rcoppa, 

That's the city set on the business. It's not an error. 

Best regards,
Darius-Sorin Bodescu
