### ISSUE TITLE
Urgent: 1.3 offer images show placeholder

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#57]
![image bug](https://cloud.githubusercontent.com/assets/11382000/7587274/5423a4ae-f8b5-11e4-836a-37b071c0357a.png)

question:why does the offer shows placeholder? and how can I delete uploaded pictures in the backend. Not replacing them but purely deleting? how does this work?

thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

The placeholder only appears if a link is not valid. That offer had 4 images, of which 3 were invalid (they were not saved in the server). This has been uploaded before our latest image fix. Please request the images to be uploaded again. We have cleared the bad images from the db. Also I would suggest you do a full check of this before approving a business. This is something that could have been checked from the backend.

Best regards,
Darius-Sorin Bodescu
