### ISSUE TITLE
urgent: 1.3 app certificate shows -present to redeem- twice if edited

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#58]
![present twice](https://cloud.githubusercontent.com/assets/11382000/7587828/6c1b797a-f8b9-11e4-8d23-99dc181b53a4.png)

**Comment by MaximilianArasin** [comment]
additional instructions 2 does not work properly. present to redeem is always displayed even if deleted and edited in the backend. 

![present bug 2](https://cloud.githubusercontent.com/assets/11382000/7587989/5428b980-f8ba-11e4-9c57-8b9dd2ce10df.png)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been fixed. The information is now being loaded as it is in the admin.

Best regards,
Darius-Sorin Bodescu
