### ISSUE TITLE
1.3 Into sharing via Facebook still shows www.getintoapp.com as source instead of just Into

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#59]
![fb sharing1](https://cloud.githubusercontent.com/assets/11382000/7627270/f382f23c-fa15-11e4-87bf-77d596ef5f08.png)
![fb sharing 2](https://cloud.githubusercontent.com/assets/11382000/7627273/f64e6eb0-fa15-11e4-99a8-32f98e090f36.png)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin, @rcoppa , @Intolucas,

This has been changed to Into, as discussed.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
still show up as getintoapp.com. please advise 

![screenshot_04](https://cloud.githubusercontent.com/assets/11382000/7676255/da604cd0-fd41-11e4-971d-be609b9d97df.jpg)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

That's the domain where the image is loaded from. Not the posted via. Please give it a look at the other posts above. That domain is where the image is loaded from, below.

Best regards,
Darius-Sorin Bodescu
