### ISSUE TITLE
Mailchimp list integration

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#6]

**Comment by rcoppa** [comment]
Sync:
- Agencies
- Talent
- Businesses

**Comment by MaximilianArasin** [comment]
Mailchimp Login:

email: max@getintoapp.com
password: Deutschland123#

**Comment by multidimensionro** [comment]
@rcoppa @MaximilianArasin The mailchimp lists have been setup and linked to the backend. We assume there are actions which should automatically subscribe (like registration or activation). Please advise if we should do auto-subscription in those cases.

**Comment by MaximilianArasin** [comment]
I will discuss with Reuben and get back to you tomorrow. Cheers

**Comment by MaximilianArasin** [comment]
@rcoppa 
I will send you the overview and email content tomorrow ..lets discuss maybe quickly after .... so your afternoon today.

cheers

**Comment by multidimensionro** [comment]
@rcoppa @MaximilianArasin 

This is live. We are working on the email content as specified in issue #2
