### ISSUE TITLE
1.3 Is it possible to edit post done via Into on Facebook afterwards on Facebook?

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#62]
it seems like you currently cannot edit post after posting. Is this a setting that we can change? that would be great. Or is it not possible to edit posts coming from a third party.

thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

Posts done via 3rd party apps can't be edited.

Best regards,
Darius-Sorin Bodescu
