### ISSUE TITLE
Backend: What are these blank spots that show up??? 

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#63]
See screenshot of line 145 and 148 and additional screenshot of upcoming offers page

![screen shot 2015-05-14 at 2 38 55 pm](https://cloud.githubusercontent.com/assets/11382000/7628518/9b4a5812-fa24-11e4-9b61-2e2808c4b459.png)
![screen shot 2015-05-14 at 3 47 46 pm](https://cloud.githubusercontent.com/assets/11382000/7628521/9d744454-fa24-11e4-9e0f-731963fde1f6.png)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

They were caused by some of our tests around the final implementation changes. They were not linked to anything and have been removed.

Best regards,
Darius-Sorin Bodescu
