### ISSUE TITLE
One code per agency - usage multiple times (limited to a quantity)

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#7]

**Comment by multidimensionro** [comment]
@rcoppa @MaximilianArasin 

This has been done in staging

**Comment by MaximilianArasin** [comment]
@multidimensionro  @rcoppa The app has been approved today.Can we move this functionality to live please. thx

**Comment by multidimensionro** [comment]
@MaximilianArasin @rcoppa 
This has been moved live and is fully functional.
