### ISSUE TITLE
Prio 3: Mail chimp sender - list talent

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#74]
please check and change to the same sender address we use for other user communication (I guess info@getintoapp.com)

**Comment by MaximilianArasin** [comment]
![screenshot_40](https://cloud.githubusercontent.com/assets/11382000/8180141/32f19570-141c-11e5-9b9c-2fa0bbebf158.png)

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been modified to "Into".

Best regards,
Darius-Sorin Bodescu
