### ISSUE TITLE
Upcoming offer - backend

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#9]
Can we please have an additional header in the backend offer tab saying "upcoming offers" with the number indicated?

Just like here: 
![screenshot_03](https://cloud.githubusercontent.com/assets/11382000/6612663/907ba458-c8d4-11e4-99ac-4317f9e45430.jpg)

Looks like this is not in place already ... otherwise we have no idea which offer we have to approve.

Thx guys
cheers
Max

**Comment by multidimensionro** [comment]
@rcoppa @MaximilianArasin 

We created the upcoming offers in the backend of the website on staging.

The pagination of the upcoming offers is still in development and we'll soon be completed.

**Comment by MaximilianArasin** [comment]
@multidimensionro 

any updates on this please? Can we move this to live?

Thx and cheers
MAx

**Comment by multidimensionro** [comment]
HI @MaximilianArasin @rcoppa,

This has been completed in staging. Please review and notify us when to move live. 

We would prefer to do this when we move everything live so that we can do a diff merge.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
Hey @multidimensionro 
thanks for this. I will double check with Reuben and decide on when to move it all to live.

@rcoppa not sure if possible, but would be great if you could arrange some testing on the multiple business procedure so that we can move it to live once it is safe to use with real clients.

thx

**Comment by multidimensionro** [comment]
@MaximilianArasin @rcoppa 
This has been moved live and is fully functional.
